development:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: fizzbuzz_dev
  username: root
  password: "rootpw"

test:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: fizzbuzz_test
  username: root
  password: "rootpw"

production:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: fizzbuzz_pro
  username: root
  password: "rootpw"

cucumber:
#  <<: *test
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: fizzbuzz_cu
  username: root
  password: "rootpw"
